# Kubernetes FizzBuzz Job
# Execute FizzBuzz as a Kubernetes Job

apiVersion: batch/v1
kind: Job
metadata:
  name: fizzbuzz
spec:
  template:
    spec:
      containers:
      - name: fizzbuzz
        image: alpine:3.19
        command: ["/bin/sh", "-c"]
        args:
        - |
          for i in $(seq 1 100); do
            if [ $((i % 15)) -eq 0 ]; then
              echo "FizzBuzz"
            elif [ $((i % 3)) -eq 0 ]; then
              echo "Fizz"
            elif [ $((i % 5)) -eq 0 ]; then
              echo "Buzz"
            else
              echo "$i"
            fi
          done
        restartPolicy: Never
  backoffLimit: 0
